/**
 * Climate Eye — Frontend State Constants
 *
 * Defines the canonical realtime states, application modes, and action types
 * for the authoritative Climate Eye frontend state model.
 *
 * Browser-safe: No Node.js core modules.
 */

export const REALTIME_STATES = Object.freeze({
  LIVE: 'LIVE',
  STALE: 'STALE',
  SIMULATED: 'SIMULATED',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const CLIMATE_MODES = Object.freeze({
  LIVE: 'LIVE',
  ANALYTICS: 'ANALYTICS',
  RISK: 'RISK',
  SIMULATION: 'SIMULATION',
  SENSOR_MESH: 'SENSOR_MESH',
  AI: 'AI',
  EMERGENCY: 'EMERGENCY',
});

export const CLIMATE_LAYERS = Object.freeze({
  SENSOR_MESH: 'SENSOR_MESH',
  TEMPERATURE: 'TEMPERATURE',
  RAINFALL: 'RAINFALL',
  SOIL_MOISTURE: 'SOIL_MOISTURE',
  AIR_QUALITY: 'AIR_QUALITY',
  WATER_LEVEL: 'WATER_LEVEL',
  FIRES: 'FIRES',
  DAMS: 'DAMS',
  EARTHQUAKES: 'EARTHQUAKES',
  GLOBAL_HAZARDS: 'GLOBAL_HAZARDS',
  HEAT_ZONES: 'HEAT_ZONES',
  FLOOD_ZONES: 'FLOOD_ZONES',
  COMPOUND_ZONES: 'COMPOUND_ZONES',
  CYCLONE_ZONES: 'CYCLONE_ZONES',
});

export const ACTION_TYPES = Object.freeze({
  NODE_UPDATED: 'NODE_UPDATED',
  NODES_UPDATED: 'NODES_UPDATED',
  NODE_REMOVED: 'NODE_REMOVED',
  TELEMETRY_UPDATED: 'TELEMETRY_UPDATED',
  REALTIME_STATE_CHANGED: 'REALTIME_STATE_CHANGED',
  SYSTEM_STATUS_CHANGED: 'SYSTEM_STATUS_CHANGED',
  LAYER_VISIBILITY_CHANGED: 'LAYER_VISIBILITY_CHANGED',
  HAZARD_UPDATED: 'HAZARD_UPDATED',
  HAZARDS_UPDATED: 'HAZARDS_UPDATED',
  PREDICTION_UPDATED: 'PREDICTION_UPDATED',
  PREDICTIONS_UPDATED: 'PREDICTIONS_UPDATED',
  COMPOUND_UPDATED: 'COMPOUND_UPDATED',
  VULNERABILITY_UPDATED: 'VULNERABILITY_UPDATED',
  EVACUATION_UPDATED: 'EVACUATION_UPDATED',
  RESPONSE_UPDATED: 'RESPONSE_UPDATED',
  SIMULATION_COMPLETED: 'SIMULATION_COMPLETED',
  SIMULATION_STATE_CHANGED: 'SIMULATION_STATE_CHANGED',
  AI_STATE_UPDATED: 'AI_STATE_UPDATED',
  GLOBAL_SOURCES_UPDATED: 'GLOBAL_SOURCES_UPDATED',
  GLOBAL_HAZARDS_UPDATED: 'GLOBAL_HAZARDS_UPDATED',
  GLOBAL_EVENTS_UPDATED: 'GLOBAL_EVENTS_UPDATED',
  GLOBAL_AI_UPDATED: 'GLOBAL_AI_UPDATED',
  UI_MODE_CHANGED: 'UI_MODE_CHANGED',
  NODE_SELECTED: 'NODE_SELECTED',
  REGION_SELECTED: 'REGION_SELECTED',
  RESET_STATE: 'RESET_STATE',
});
