"""
Hazard domain types and output contracts for Climate Eye View S2.
Defines strict Pydantic schemas for deterministic hazard results.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator
from intelligence.core.contracts.telemetry import LocationCoordinate


class HazardType(str, Enum):
    HEAT = "heat"
    FLOOD = "flood"
    DROUGHT = "drought"


class HazardStatus(str, Enum):
    DETECTED = "DETECTED"
    NOT_DETECTED = "NOT_DETECTED"
    UNAVAILABLE = "UNAVAILABLE"


class HazardClassification(str, Enum):
    NORMAL = "NORMAL"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class HazardResult(BaseModel):
    """
    Structured, deterministic hazard evaluation result.
    Generated by S2 hazard intelligence models from normalized telemetry.
    """
    hazard_id: str = Field(..., min_length=1, description="Unique hazard evaluation identifier")
    hazard: HazardType = Field(..., description="Hazard domain classification (heat, flood, drought)")
    severity: float = Field(..., ge=0.0, le=1.0, description="Normalized hazard severity score [0.0, 1.0]")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Data quality and model confidence score [0.0, 1.0]")
    classification: Optional[HazardClassification] = Field(default=None, description="Categorical risk tier (NORMAL, LOW, MODERATE, HIGH, CRITICAL)")
    status: HazardStatus = Field(..., description="Detection status (DETECTED, NOT_DETECTED, UNAVAILABLE)")
    timestamp: datetime = Field(..., description="Timestamp of the evaluated observation")
    forecast_horizon_minutes: int = Field(default=0, ge=0, description="Prediction horizon in minutes (strictly 0 for Phase 2 detection)")
    location: LocationCoordinate = Field(..., description="WGS84 location of the observation")
    features: Dict[str, Any] = Field(default_factory=dict, description="Raw and transformed model features with units")
    drivers: List[str] = Field(default_factory=list, description="Deterministic, rule-based drivers explaining risk severity")
    source: str = Field(default="model", description="Originating engine designation")
    model_version: str = Field(..., min_length=1, description="Immutable model version string (e.g. heat-v1, flood-v1, drought-v1)")
    simulated: bool = Field(default=False, description="Flag indicating whether input was synthetic/simulated (strictly false in Phase 2)")
    provenance_hash: Optional[str] = Field(default=None, description="SHA-256 fingerprint linking result to input telemetry")
    reason: Optional[str] = Field(default=None, description="Explanation when status is UNAVAILABLE or quality gate fails")

    @field_validator("forecast_horizon_minutes")
    @classmethod
    def validate_horizon_zero(cls, v: int) -> int:
        if v != 0:
            raise ValueError(f"forecast_horizon_minutes must be 0 for Phase 2 current-state detection (got {v})")
        return v

    @field_validator("simulated")
    @classmethod
    def validate_simulated_false(cls, v: bool) -> bool:
        if v is True:
            raise ValueError("simulated must be False for Phase 2 production telemetry evaluation")
        return v


class HazardEvaluationRequest(BaseModel):
    """API payload schema for hazard evaluation."""
    telemetry: Dict[str, Any] = Field(..., description="Raw or normalized telemetry dictionary conforming to NormalizedTelemetry")


class HazardEvaluationResponse(BaseModel):
    """API response schema containing independent hazard evaluations."""
    success: bool = Field(default=True)
    hazards: List[HazardResult] = Field(default_factory=list, description="Array of independent hazard evaluations")
    request_id: Optional[str] = Field(default=None, description="Unique request tracing ID")
    evaluated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of evaluation execution",
    )
